### ISSUE TITLE
support lifecycle prefix

### ISSUE THREAD

**Issue by andrewharvey** [jakecoppinger/australian-cycleway-stats#3]
`proposed:highway=*` and `construction:highway=*` are commonly used in addition to `highway=proposed`, and in some cases where something exists and it's being proposed to change it, lifecycle prefix is the only way to tag it.

It does appear in the database, eg in NSW https://overpass-turbo.eu/s/1EDk

**Comment by jakecoppinger** [comment]
Thanks very much for this, updated!
