### ISSUE TITLE
Consider `cycleway:both` tags

### ISSUE THREAD

**Issue by samcantwell** [jakecoppinger/australian-cycleway-stats#5]
Many bike lanes in Melbourne have recently been mapped with the `cycleway:both` tag rather than the `cycleway` tag. This should also be counted when bike lane length is calculated.

**Comment by jakecoppinger** [comment]
Thanks very much for this! I'm on holidays but will be back in a few days - I'll update when I've fixed.

**Comment by samcantwell** [comment]
I’m happy to submit a PR soon with a quick fixOn 4 Jan 2024, at 07:32, Jake Coppinger ***@***.***> wrote:﻿
Thanks very much for this! I'm on holidays but will be back in a few days - I'll update when I've fixed.
